# Generated by Django 5.0.6 on 2024-06-14 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_studentquizresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquizresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
